name: 'Orleans build y push'
#on:
#  push:
#    branches:
#      - main
#      - testBuild
#    tags:
#      - 'test*'
#on:
# push:
#    branches:
#      - main
#    paths:
#      - "grains/**"
inputs:
  ACR_USERNAME:
    description: "user de acr"
    required: true
    default: ''
  ACR_PASSWORD:
    description: "passwrd de acr"
    required: true
    default: ''
  ACR_NAME:
    description: "nommbre del acr"
    required: true
    default: ''
  ACR_FULL_NAME:
    description: "nombre del acr con azurecr.io"
    required: true
    default: ''
  variable:
    description: "variables que recibo de la llamada al pipeline"
    required: true
  appName:
    description: "Nombre de la aplicacion (dentro del proyecto)"
    required: true
    default: orleans-grain
  teamProject:
    description: "Nombre del proyecto/equipo"
    required: true
    default: qa
  appVersion:
    description: "tag para subir imagen"
    required: true
    default: latest


      
#env:
  #Es un valor que viene del secreto, pero el install de helm lo espera cmo variable 'plana'
#  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
runs:
  using: "composite"
  steps:
      - run: echo hi!, we working.
        shell: bash
        # Setup .NET Core SDK
      - name: checkout
        uses: actions/checkout@v3.5.0 #actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setear docker
        uses: docker/setup-buildx-action@v3
        with:
           install: true
      - name: Run a multi-line script
        shell: bash
        run: |-
          echo  ${{ inputs.ACR_USERNAME }}
          echo ${{ inputs.ACR_PASSWORD }}
          echo ${{inputs.teamProject}}-${{inputs.appName}}
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.ACR_NAME }}.azurecr.io #ACR_FULL_NAME incluye el azurecr.io
          username: ${{ inputs.ACR_USERNAME }}
          password: ${{ inputs.ACR_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . #Orleanspoc-main
          file: Dockerfile #Orleanspoc-main/Dockerfile
          push: true
#          tags: ${{ inputs.DOCKERHUB_USERNAME }}/test:latest
          tags: ${{ inputs.ACR_FULL_NAME }}/${{inputs.teamProject}}-${{inputs.appName}}:${{ inputs.appVersion}}

