name: 'Orleans helm package'
inputs:
  APPS_ARO_CERTIFICATE:
    description: "Certificado para el dominio de apps en ARO"
    required: true
  APPS_ARO_CA_CERTIFICATE:
    description: "Certificado de la CA"
    required: true
  APPS_ARO_KEY_CERTIFICATE:
    description: "Certificado ARO Key"
    required: true
  ACR_USERNAME:
    description: "user de acr"
    required: true
    default: ''
  ACR_PASSWORD:
    description: "passwrd de acr"
    required: true
    default: ''
#  ACR_NAME:
#    description: "nommbre del acr"
#    required: true
#    default: ''
  ACR_FULL_NAME:
    description: "nombre del acr con azurecr.io"
    required: true
    default: ''
  variable:
    description: "variables que recibo de la llamada al pipeline"
    required: false
  appName:
    description: "Nombre de la aplicacion (dentro del proyecto)"
    required: true
    default: orleans-grain
  teamProject:
    description: "Nombre del proyecto/equipo"
    required: true
    default: qa
  appVersion:
    description: "tag para subir imagen"
    required: true
    default: latest
#  GITHUB_TOKEN:
#    description: "Secret que helm necesita"
#    required: true
  GITHUB_HELMREPO_TOKEN:
    description: "Token para descargar el codigo de templates HELM"
    required: true
  helmChartVersionLatestQa:
     description: "VersionHelm"
     required: true
  appVersionGit:
     description: "VersionGit"
     required: true
  clusterFqdn:
     description: "FQDN para pasarle a helm"
     required: true
      
#env:
  #Es un valor que viene del secreto, pero el install de helm lo espera cmo variable 'plana'
#  GITHUB_TOKEN: ${{ inputs.GITHUB_TOKENB }}
runs:
  using: "composite"
  steps:
      - run: echo 'Inicia el proceso'
        shell: bash
#Si tenemos un runner con Helm instalado no haria falta
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3 #Helm 13 tiene un bug
#        with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#Obtengo el codigo base remoto para los manifiestos


      - name: Checkout code helm templates
        uses: actions/checkout@v3.5.0
        with:
          repository: infrastructure-services/poc-orleans
          ref: main
#          token: ${{ inputs.GITHUB_HELMREPO_TOKEN }}
          ssh-key: ${{ inputs.GITHUB_HELMREPO_TOKEN }}
      - name: copio Chart y values (y templates)
        shell: bash
        run: |-
           ls
           cp Chart.yaml ../Chart.yaml
           cp -R templates ../templates
           ls ../
      - name: checkout codigo desarrollador
        uses: actions/checkout@v3.5.0 #actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Traigo los archivos al repo actual
        shell: bash
        run: |-
           ls ../
           cp .devops/value-qa.yaml values.yaml
           cp ../Chart.yaml Chart.yaml 
           cp -R ../templates templates
      - name: Reviso archivos y version helm
        shell: bash
        run: |-
           ls
           helm version --short
      - name: Helm customizer le agregan valores al values y al chart
        shell: bash
        run: |-
          echo -e 'cluster:\n  fqdn: ${{ inputs.clusterFqdn}}' >> values.yaml
          echo 'namespace: ${{inputs.TeamProject}}-qa' >> values.yaml
          echo 'appname: ${{inputs.appName}}' >> values.yaml
          echo 'caCertificate: |' >> values.yaml
          echo ${{inputs.APPS_ARO_CA_CERTIFICATE}} | sed 's/^/    /' >> values.yaml
          cat values.yaml
          echo 'certificate: |' >> values.yaml
          echo ${{inputs.APPS_ARO_CERTIFICATE}} | sed 's/^/    /' >> values.yaml
          cat values.yaml
          echo 'key: |' >> values.yaml
          echo ${{inputs.APPS_ARO_KEY_CERTIFICATE}} |  sed 's/^/    /' >> values.yaml
          cat values.yaml
          echo 'name: ${{inputs.TeamProject}}-${{inputs.appName}}' >> Chart.yaml
      - name: Helm Lint, verifica helm por errores (deberia ser bloqueante)
        shell: bash
        run: |-
          helmLint="helm lint --values=values.yaml > /dev/null 2>&1"
          if eval "$helmLint"; then
             echo "HELM Lint OK - The template folder and values file format is OK";
          else
             echo "HELM Lint FAIL - There is a problem with the folder 'templates' or the values file format";
             exit 1
          fi
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.ACR_NAME }}.azurecr.io #ACR_FULL_NAME incluye el azurecr.io
          username: ${{ inputs.ACR_USERNAME }}
          password: ${{ inputs.ACR_PASSWORD }}
      - name: Enpaquetar y subir helm a acr
        shell: bash
        run: |-
          export HELM_EXPERIMENTAL_OCI=1 #Es necesario para el chart save}}
          helm package --version ${{ inputs.helmChartVersionLatestQa}} --app-version ${{ inputs.appVersionGit}} --namespace ${{ inputs.TeamProject}}-qa .
          echo '${{ inputs.ACR_PASSWORD }}' | helm registry login ${{ inputs.ACR_FULL_NAME}} --username ${{ inputs.ACR_USERNAME}} --password-stdin
          helm push ${{inputs.TeamProject}}-${{inputs.appName }}-${{inputs.helmChartVersionLatestQa}}.tgz  oci://${{inputs.ACR_FULL_NAME }}/helm/ # ${{ inputs.TeamProject}}-${{ inputs.appName}}  # :${{ env.helmChartVersionLatestQa}}

           
